// src/lib/ai/accountant.ts
import { LLMClient, LLMMessage } from './llm'
import { AgentTools } from './tools'

const SYSTEM_PROMPT = `You are AdullamBank Accountant Agent — a professional financial analyst AI assistant. You specialize in analyzing financial data and producing detailed, actionable reports. Be precise, professional, and reference actual numbers from the data provided.`

export class AccountantAgent {
  private llm: LLMClient
  private tools: AgentTools

  constructor(userId: string) {
    this.llm = new LLMClient()
    this.tools = new AgentTools(userId)
  }

  async chatStream(
    message: string,
    onChunk: (chunk: string) => void
  ): Promise<{ response: string }> {
    const data = await this.gatherFinancialData()
    const contentPrompt = `${message}\n\nUse the following real financial data to respond:\n${JSON.stringify(data, null, 2)}`

    const messages: LLMMessage[] = [
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: contentPrompt },
    ]

    const response = await this.llm.chatStream(messages, onChunk)
    return { response: response.choices[0]?.message?.content || 'Analysis complete.' }
  }

  private async gatherFinancialData() {
    try {
      const [balances, stats, transactions] = await Promise.all([
        this.tools.getAccountBalances(),
        this.tools.getTransactionStats({ period: 'month' }),
        this.tools.getTransactions({ limit: 20 }),
      ])
      return { balances, stats, transactions }
    } catch {
      return { balances: null, stats: null, transactions: null }
    }
  }

  async generateFinancialReport(): Promise<string> {
    const data = await this.gatherFinancialData()

    const prompt = `Generate a detailed monthly financial report in markdown format based on this data:

${JSON.stringify(data, null, 2)}

Format:
# Financial Report — This Month

## Account Overview
[Table with accounts and balances]

## Cash Flow Summary
[Income, expenses, net flow]

## Recent Transactions
[List of recent transactions]

## Financial Health
[Score and indicators]

## Recommendations
[Actionable advice]

Use markdown tables, headers, and bullet points.`

    const response = await this.llm.chat([
      { role: 'system', content: SYSTEM_PROMPT },
      { role: 'user', content: prompt },
    ])

    return `${response.choices[0]?.message?.content || 'Report generation failed.'}\n\n---\n*Generated by AdullamBank AI Accountant*`
  }

  reset(): void {}
}